# HTTP Server配置
server:
  address:             ":8199"
  serverRoot:          "resource/public"
  dumpRouterMap:       true
  routeOverWrite:      true
  accessLogEnabled:    true
  openapiPath:         "/api.json"
  swaggerPath:         "/swagger"

# 全局日志配置
logger:
    level : "all"
    stdout: true

# 数据库连接
database:
  logger:
    path:    "logs/sql"
    level:   "all"
    stdout:  true
    ctxKeys: ["RequestId"]

  default:
    link:   "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
    debug:  true

# GF-CLI工具配置
gfcli:
  # dao生成
  gen:
    dao:
    - link:            "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
      tables:          "user"
      removePrefix:    "gf_"
      descriptionTag:  true
      noModelComment:  true
